/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    docsSidebar: [
        {
            type: 'category',
            label: 'Engine',
            link: {
                type: 'generated-index',
                title: 'Engine Documentation',
                description: '884 pages',
                slug: '/engine',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'engine',
                },
            ],
        },
        {
            type: 'category',
            label: 'Foundation',
            link: {
                type: 'generated-index',
                title: 'Foundation Documentation',
                description: '7 pages',
                slug: '/foundation',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'foundation',
                },
            ],
        },
        {
            type: 'category',
            label: 'Script',
            link: {
                type: 'generated-index',
                title: 'Script Documentation',
                description: '770 pages',
                slug: '/script',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'script',
                },
            ],
        },
    ],
};

module.exports = sidebars;


